### ISSUE TITLE
Is it a project you will maintain?

### ISSUE THREAD

**Issue by frederikhors** [pavish/select-madu#12]
Is it a project you will maintain?

**Comment by pavish** [comment]
At the moment, no. I will be looking to maintain this project at a later point of time, but as of now I'm not giving this any priority. There are other projects you could use like svelte-select.

If you have any particular use case that the other projects do not satisfy, please feel free to mention it. That would give me a reason to show this project some attention.

**Comment by pavish** [comment]
I have decided to maintain this project and I'm working on v2.0.0, with some new additions and fixes. The feature release cycle will be slow, except for accessibility and security related fixes.
